name: test-health-action
on: 
  - push

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: A job to say hello
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - id: foo
        uses: flavioaandres/health-monitor-action@v0.0.1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash