name: test-health-action
on: 
  - push

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: test health
    steps:
      - id: foo
        uses: "condorlabs-actions/health-availability@1.0.6"
        with:
          apps_inventory_url: 'https://apps-inventory.test.cebroker.com/apps/providers_roster_api?sections=health&secondsAgo=30'
          apps_inventory_auth: 'zeD3qUwspYmzPyUcE7fKE8jT2qUgCrWd'
          availability_percentage: 80
      - run: echo ${{ steps.foo.outputs.summary }}
