name: test-health-action
on: 
  - push

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: A job to say hello
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - id: foo
        uses: "condorlabs-actions/health-availability@1.0.1-check-warns"
        with:
          apps_inventory_url: 'https://17pp30p17d.execute-api.us-east-1.amazonaws.com/test/apps/providers_roster_api?sections=health&secondsAgo=30'
          apps_inventory_auth: 'zeD3qUwspYmzPyUcE7fKE8jT2qUgCrWd'
          allow_warn_as_pass: true
          availability_percentage: 80
      - run: echo ${{ steps.foo.outputs.summary }}
