name: test-health-action
on: 
  - push

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: A job to say hello
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - id: foo
        uses: flavioaandres/health-monitor-action@v0.0.2
        with:
          apps_inventory_url: 'https://17pp30p17d.execute-api.us-east-1.amazonaws.com/test'
          apps_inventory_auth: 'zeD3qUwspYmzPyUcE7fKE8jT2qUgCrWd'
          availability_percentage: 80
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
